name: invent
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0-318.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.9.2  # Adding flutter_launcher_icons under dev_dependencies

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"  # Specify your custom app icon path here

flutter:
  uses-material-design: true
  assets:
    - assets/icons/app_icon.png  # Ensure the app icon is added as an asset

